import 'package:share_plus/share_plus.dart';
import '../models/medicine.dart';
import '../models/bill_analysis.dart';

class ReportService {
  void shareMedicineReport(Medicine medicine) {
    final buffer = StringBuffer();
    buffer.writeln('MEDICINE REPORT');
    buffer.writeln('=' * 30);
    buffer.writeln();
    buffer.writeln('Name: ${medicine.name}');
    buffer.writeln();

    if (medicine.chemicalContents.isNotEmpty) {
      buffer.writeln('Chemical Contents:');
      for (final content in medicine.chemicalContents) {
        buffer.writeln('  - $content');
      }
      buffer.writeln();
    }

    buffer.writeln('General Use:');
    buffer.writeln(medicine.generalUse);
    buffer.writeln();

    if (medicine.expiryDate != null && medicine.expiryDate!.isNotEmpty) {
      buffer.writeln(
          'Expiry Date: ${medicine.expiryDate}${medicine.isExpired ? " (EXPIRED)" : ""}');
      buffer.writeln();
    }

    if (medicine.manufactureDate != null &&
        medicine.manufactureDate!.isNotEmpty) {
      buffer.writeln('Manufacture Date: ${medicine.manufactureDate}');
      buffer.writeln();
    }

    if (medicine.harmfulContents.isNotEmpty) {
      buffer.writeln('Harmful Content Warnings:');
      for (final harmful in medicine.harmfulContents) {
        buffer.writeln(
            '  - ${harmful.substance}${harmful.isSuspicious ? " [SUSPICIOUS]" : ""}');
        buffer.writeln('    ${harmful.description}');
      }
      buffer.writeln();
    }

    if (medicine.agePrecautions.isNotEmpty) {
      buffer.writeln('Age Precautions:');
      for (final precaution in medicine.agePrecautions) {
        buffer.writeln('  - $precaution');
      }
      buffer.writeln();
    }

    if (medicine.interactionWarning != null &&
        medicine.interactionWarning!.isNotEmpty) {
      buffer.writeln('Drug Interaction Warning:');
      buffer.writeln(medicine.interactionWarning);
      buffer.writeln();
    }

    buffer.writeln('Generated by Med Lab');

    Share.share(buffer.toString());
  }

  void shareBillReport(BillAnalysis bill) {
    final buffer = StringBuffer();
    buffer.writeln('MEDICAL BILL ANALYSIS');
    buffer.writeln('=' * 30);
    buffer.writeln();
    buffer.writeln('Hospital: ${bill.hospitalName}');
    if (bill.totalAmount != null) {
      buffer.writeln('Total Amount: \$${bill.totalAmount!.toStringAsFixed(2)}');
    }
    buffer.writeln('Verdict: ${bill.overallVerdict.toUpperCase()}');
    buffer.writeln();
    buffer.writeln('Summary:');
    buffer.writeln(bill.summary);
    buffer.writeln();

    if (bill.issues.isNotEmpty) {
      buffer.writeln('Issues Found (${bill.issues.length}):');
      for (final issue in bill.issues) {
        buffer.writeln(
            '  - [${issue.severity.toUpperCase()}] ${issue.itemName} (${issue.issueTypeLabel})');
        buffer.writeln('    ${issue.description}');
      }
      buffer.writeln();
    }

    buffer.writeln('Recommendation:');
    buffer.writeln(bill.recommendation);
    buffer.writeln();
    buffer.writeln('Generated by Med Lab');

    Share.share(buffer.toString());
  }
}
